=== carriercomm/OXadminGUI/web/xml/text.dtd
<?xml version='1.0' encoding='utf-8'?>


<!ELEMENT content (group)+>

<!ELEMENT group (text)+>
<!ATTLIST group
  name CDATA  #REQUIRED
>

<!ELEMENT text (lang)+>
<!ATTLIST text
  id CDATA  #REQUIRED
>

<!ELEMENT lang (#PCDATA) >
<!ATTLIST lang
  id (de | en | fr | it | es | pl | nl | sys ) #REQUIRED
>

=== carriercomm/OXadminGUI/web/xml/content.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE content SYSTEM "text.dtd" >

<content>
    <group name="general">
         <text id="context">
            <lang id="es">Contexto</lang>        
            <lang id="de">Kontext</lang>
            <lang id="en">Context</lang>
            <lang id="it">Context</lang>
            <lang id="fr">Context</lang>
            <lang id="nl">Context</lang>
         </text>

        <text id="user">
            <lang id="es">Usuario</lang>
            <lang id="de">Benutzer</lang>
            <lang id="en">User</lang>
            <lang id="it">Utente</lang>
            <lang id="fr">User</lang>
            <lang id="nl">Gebruiker</lang>
        </text>

        <text id="group">
            <lang id="es">Grupo</lang>
            <lang id="de">Gruppen</lang>
            <lang id="en">Group</lang>
            <lang id="it">Gruppo</lang>
            <lang id="fr">Group</lang>
            <lang id="nl">Groep</lang>
        </text>

        <text id="groups">
            <lang id="es">Grupos</lang>
            <lang id="de">Gruppen</lang>
            <lang id="en">Groups</lang>
            <lang id="it">Gruppi</lang>
            <lang id="fr">Groups</lang>
            <lang id="nl">Groepen</lang>
         </text>

        <text id="resource">
            <lang id="es">Recurso</lang>        
            <lang id="de">Ressourcen</lang>
            <lang id="en">Resource</lang>
            <lang id="it">Risorsa</lang>
            <lang id="fr">Resource</lang>
            <lang id="nl">Contacten</lang>
        </text>

        <text id="info">
            <lang id="es">Información</lang>
            <lang id="de">Information</lang>
            <lang id="en">Information</lang>
            <lang id="it">Informazioni</lang>
            <lang id="fr">Information</lang>
            <lang id="nl">Informatie</lang>
        </text>

        <text id="logout">
            <lang id="es">Salir</lang>
            <lang id="de">Logout</lang>
            <lang id="en">Logout</lang>
            <lang id="it">Logout</lang>
            <lang id="fr">Logout</lang>
            <lang id="nl">Afmelden</lang>
        </text>

        <text id="create">
            <lang id="es">Crear</lang>
            <lang id="de">Anlegen</lang>
            <lang id="en">Create</lang>
            <lang id="it">Crea</lang>
            <lang id="fr">Create</lang>
            <lang id="nl">Maak</lang>
        </text>

        <text id="set">
            <lang id="es">Seleccionar</lang>
            <lang id="de">Setzen</lang>
            <lang id="en">Set</lang>
            <lang id="it">Imposta</lang>
            <lang id="fr">Set</lang>
            <lang id="nl">Selecteer</lang>
        </text>

        <text id="change">
            <lang id="es">Modificar</lang>
            <lang id="de">Ändern</lang>
            <lang id="en">Change</lang>
            <lang id="it">Modifica</lang>
            <lang id="fr">Change</lang>
            <lang id="nl">Wijzig</lang>
        </text>

        <text id="dismiss">
            <lang id="es">Cancelar</lang>
            <lang id="de">Änderungen verwerfen</lang>
            <lang id="en">Dismiss</lang>
            <lang id="it">Annulla</lang>
            <lang id="fr">Dismiss</lang>
            <lang id="nl">Annuleer</lang>
        </text>

        <text id="delete">
            <lang id="es">Borrar</lang>
            <lang id="de">Löschen</lang>
            <lang id="en">Delete</lang>
            <lang id="it">Cancella</lang>
            <lang id="fr">Delete</lang>
            <lang id="nl">Verwijder</lang>
        </text>

        <text id="activate">
            <lang id="es">Habilitar</lang>
            <lang id="de">Aktivieren</lang>
            <lang id="en">Enable</lang>
            <lang id="it">Abilita</lang>
            <lang id="fr">Enable</lang>
            <lang id="nl">Activeer</lang>
        </text>

        <text id="setContextAdmin">
            <lang id="es">Seleccionar Administrador de Contexto</lang>
            <lang id="de">ContextAdmin setzen</lang>
            <lang id="en">Set ContextAdmin</lang>
            <lang id="it">Imposta il ContextAdmin</lang>
            <lang id="fr">Set ContextAdmin</lang>
            <lang id="nl">Selecteer context</lang>
        </text>

        <text id="noworkingCTX">
            <lang id="es">No ha seleccionado un contexto de trabajo. Por favor, utilice el menú contextual para seleccionar el contexto de trabajo!</lang>
            <lang id="de">Es ist kein aktueller Kontext gesetzt. Setzen Sie bitte über das Menü Kontext einen Kontext!</lang>
            <lang id="en">No working context is set. Please use menu context for setting the working context!</lang>
            <lang id="it">Non è stato impostato nessun context operativo. Si prega di utilizza il menu context per impostare il context operativo!</lang>
            <lang id="fr">No working context is set. Please use menu context for setting the working context!</lang>
            <lang id="nl">Er is geen context gezet. Selecteer een context in het Context menu!</lang>
        </text>

        <text id="name">
            <lang id="es">Nombre</lang>
            <lang id="de">Name</lang>
            <lang id="en">Name</lang>
            <lang id="it">Nome</lang>
            <lang id="fr">Name</lang>
            <lang id="nl">Naam</lang>
        </text>

        <text id="quota">
            <lang id="es">Cuota</lang>
            <lang id="de">Kontigent</lang>
            <lang id="en">Quota</lang>
            <lang id="it">Quota</lang>
            <lang id="fr">Quota</lang>
            <lang id="nl">Limiet</lang>
        </text>

        <text id="mapping">
            <lang id="es">Asignación</lang>
            <lang id="de">Zuordnung</lang>
            <lang id="en">Mapping</lang>
            <lang id="it">Mapping</lang>
            <lang id="fr">Mapping</lang>
            <lang id="nl">Koppelingen</lang>
        </text>

        <text id="rights">
            <lang id="es">Permisos</lang>
            <lang id="de">Rechte</lang>
            <lang id="en">Rights</lang>
            <lang id="it">Permessi</lang>
            <lang id="fr">Rights</lang>
            <lang id="nl">Rechten</lang>
        </text>

        <text id="active">
            <lang id="es">Habilitado</lang>            
            <lang id="de">Aktiv</lang>
            <lang id="en">Enabled</lang>
            <lang id="it">Abilitato</lang>
            <lang id="fr">Enabled</lang>
            <lang id="nl">Actief</lang>
        </text>

        <text id="login">
            <lang id="es">Iniciar sesión</lang>            
            <lang id="de">Login</lang>
            <lang id="en">Login</lang>
            <lang id="it">Login</lang>
            <lang id="fr">Login</lang>
            <lang id="nl">Aanmelden</lang>
        </text>

        <text id="yes">
            <lang id="es">Si</lang>
            <lang id="de">Ja</lang>
            <lang id="en">Yes</lang>
            <lang id="it">Si</lang>
            <lang id="fr">Yes</lang>
            <lang id="nl">Ja</lang>
        </text>

        <text id="no">
            <lang id="es">No</lang>
            <lang id="de">Nein</lang>
            <lang id="en">No</lang>
            <lang id="it">No</lang>
            <lang id="fr">No</lang>
            <lang id="nl">Nee</lang>
        </text>

        <text id="noctxselected">
            <lang id="es">¡Error: Contexto no seleccionado!</lang>
            <lang id="de">Fehler: Kein Kontext ausgewählt!</lang>
            <lang id="en">Error: No context selected!</lang>
            <lang id="it">Errore: Nessun context selezionato!</lang>
            <lang id="fr">Error: No context selected!</lang>
            <lang id="nl">Fout: Geen context geselecteerd!</lang>
        </text>

        <text id="morectxselected">
            <lang id="es">¡Error: Más de un Contexto seleccionado!</lang>
            <lang id="de">Fehler: Es wurde mehr als ein Kontext ausgewählt!</lang>
            <lang id="en">Error: More than one context selected!</lang>
            <lang id="it">Errore: E' stato selezionato più di un context!</lang>
            <lang id="fr">Error: More than one context selected!</lang>
            <lang id="nl">Fout: Meer dan een context geselecteerd!</lang>
        </text>

        <text id="noctxadmin">
            <lang id="es">Error: Faltan datos en la cuenta de administrador de contexto!\nPor favor, el menú 'Seleccionar Administrador de Contexto' para fijar estos datos</lang>
            <lang id="de">Fehler: Für diesen Kontext sind keine Account-Daten für den ContextAdmin vorhanden!\nBitte setzen Sie diese Daten über den Menüpunkt 'ContextAdmin setzen'.</lang>
            <lang id="en">Error: Missing context admin account data!\nPlease the menu 'Set ContextAdmin' to set this data.</lang>
            <lang id="it">Errore: Non sono presenti i dati dell'account del Context admin!\nSi prega di utilizzare il menu 'Imposta il ContextAdmin' per impostare questi dati.</lang>
            <lang id="fr">Error: Missing context admin account data!\nPlease the menu 'Set ContextAdmin' to set this data.</lang>
            <lang id="nl">Fout: Ontbrekende context!\nSelecteer een context om te beheren in menu Context.</lang>
        </text>

        <text id="ctxadminset">
            <lang id="es">El Administrador de Contexto ya está seleccionado!\nPara cambiar el Administrador de Contexto por favor use el menú de usuario.</lang>
            <lang id="de">Der ContextAdmin für diesen Kontext ist schon gesetzt!\nWenn Sie den ContextAdmin ändern wollen, benutzen Sie das Menü Benutzer.</lang>
